#!/bin/bash

GOPATH="$HOME/workspace/go"
SRCDIR="$GOPATH/src"
BINDIR="$GOPATH/bin"
PKGDIR="$GOPATH/pkg"


mkdir -p $SRCDIR
mkdir -p $BINDIR
mkdir -p $PKGDIR

echo "export GOPATH=$GOPATH" >> ~/.bashrc
echo "export PATH=$PATH:$GOPATH/bin" >> ~/.bashrc
source ~/.bashrc 

